apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-kzqk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-kzqk
    app.kubernetes.io/part-of: test-app-fzxe
  name: devfile-sample-python-basic-kzqk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-kzqk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-kzqk
    spec:
      containers:
      - image: quay.io/lucarval-rhtap/yolo/test-app-fzxe/devfile-sample-python-basic-kzqk@sha256:30753e04ed799fffbd0ea06a3640741217f6a6e25248d83c5a7fbca34dcce22f
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
